export const ANALYTICS_EVENTS = {
  SCREEN_VIEW_WELCOME: 'screen_view_welcome',
  SCREEN_VIEW_LOGIN: 'screen_view_login',
  SCREEN_VIEW_REGISTER: 'screen_view_register',
  SCREEN_VIEW_FORGOT_PASSWORD: 'screen_view_forgot_password',
  SCREEN_VIEW_RESET_PASSWORD: 'screen_view_reset_password',
  SCREEN_VIEW_HOME: 'screen_view_home',
  SCREEN_VIEW_SEARCH: 'screen_view_search',
  SCREEN_VIEW_PROVIDER_DETAILS: 'screen_view_provider_details',
  SCREEN_VIEW_BOOKING: 'screen_view_booking',
  SCREEN_VIEW_PAYMENT: 'screen_view_payment',
  SCREEN_VIEW_BOOKINGS: 'screen_view_bookings',
  SCREEN_VIEW_PROFILE: 'screen_view_profile',

  CTA_CLICK_LOGIN_START: 'cta_click_login_start',
  CTA_CLICK_REGISTER_START: 'cta_click_register_start',
  CTA_CLICK_FORGOT_PASSWORD_START: 'cta_click_forgot_password_start',
  CTA_CLICK_RESET_PASSWORD_START: 'cta_click_reset_password_start',
  CTA_CLICK_PRE_REGISTRATION_START: 'cta_click_pre_registration_start',
  CTA_CLICK_LOGOUT: 'cta_click_logout',
  CTA_CLICK_BOOK_NOW: 'cta_click_book_now',
  CTA_CLICK_PAY_NOW: 'cta_click_pay_now',
  CTA_CLICK_RETRY_PAYMENT: 'cta_click_retry_payment',
  CTA_CLICK_SEARCH_TAG: 'cta_click_search_tag',
  CTA_CLICK_PROVIDER_CARD: 'cta_click_provider_card',

  FORM_SUBMIT_LOGIN: 'form_submit_login',
  FORM_SUBMIT_REGISTER: 'form_submit_register',
  FORM_SUBMIT_FORGOT_PASSWORD: 'form_submit_forgot_password',
  FORM_SUBMIT_RESET_PASSWORD: 'form_submit_reset_password',
  FORM_ERROR_LOGIN: 'form_error_login',
  FORM_ERROR_REGISTER: 'form_error_register',
  FORM_ERROR_FORGOT_PASSWORD: 'form_error_forgot_password',
  FORM_ERROR_RESET_PASSWORD: 'form_error_reset_password',
  FORM_SUBMIT_PRE_REGISTRATION: 'form_submit_pre_registration',
  FORM_ERROR_PRE_REGISTRATION: 'form_error_pre_registration',

  AUTH_LOGIN_SUCCESS: 'auth_login_success',
  AUTH_LOGIN_FAILED: 'auth_login_failed',
  AUTH_REGISTER_SUCCESS: 'auth_register_success',
  AUTH_REGISTER_FAILED: 'auth_register_failed',
  AUTH_PASSWORD_RESET_REQUEST_SUCCESS: 'auth_password_reset_request_success',
  AUTH_PASSWORD_RESET_REQUEST_FAILED: 'auth_password_reset_request_failed',
  AUTH_PASSWORD_RESET_WITH_CODE: 'auth_password_reset_with_code',
  AUTH_PASSWORD_RESET_SUCCESS: 'auth_password_reset_success',
  AUTH_PASSWORD_RESET_FAILED: 'auth_password_reset_failed',

  BOOKING_DRAFT_CREATED: 'booking_draft_created',
  BOOKING_STEP_COMPLETED: 'booking_step_completed',
  BOOKING_STEP_ABANDONED: 'booking_step_abandoned',
  BOOKING_UPDATED: 'booking_updated',
  BOOKING_CANCELLED: 'booking_cancelled',

  PAYMENT_INTENT_STARTED: 'payment_intent_started',
  PAYMENT_COMPLETED: 'payment_completed',
  PAYMENT_FAILED: 'payment_failed',
  EMPTY_STATE_VIEWED: 'empty_state_viewed',
} as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
